// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhCW-cwOPMbju4NwDU5SKrCnm8xzC_FSk',
    appId: '1:894283814501:web:cbd808516dd85fbc35988c',
    messagingSenderId: '894283814501',
    projectId: 'loopi-e8f3b',
    authDomain: 'loopi-e8f3b.firebaseapp.com',
    storageBucket: 'loopi-e8f3b.firebasestorage.app',
    measurementId: 'G-F35WPSLQV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBibwSFxU7k0_3vZwQ_gqVfmU_OtdcrK8M',
    appId: '1:894283814501:android:ace916d60a8fa3c935988c',
    messagingSenderId: '894283814501',
    projectId: 'loopi-e8f3b',
    storageBucket: 'loopi-e8f3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfM--20tsVdUB7omZCEgpUYG2JGXukECA',
    appId: '1:894283814501:ios:dccccf0a59394b3835988c',
    messagingSenderId: '894283814501',
    projectId: 'loopi-e8f3b',
    storageBucket: 'loopi-e8f3b.firebasestorage.app',
    iosBundleId: 'com.example.loopiAdmin',
  );
}
